// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Y_sG8sRqtfIdcNcDPEaA32xZ7U2sdKA',
    appId: '1:975792738502:web:063d5282ca8cac2ac8c7c7',
    messagingSenderId: '975792738502',
    projectId: 'test-5f00d',
    authDomain: 'test-5f00d.firebaseapp.com',
    storageBucket: 'test-5f00d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTw0WF2PBFKLfBt0PljOkGPZ-WwbrUV0',
    appId: '1:975792738502:android:8bb04886f5897103c8c7c7',
    messagingSenderId: '975792738502',
    projectId: 'test-5f00d',
    storageBucket: 'test-5f00d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiiZXYccNa5X8ChO07Yz_QMvTrJ4DmR1c',
    appId: '1:975792738502:ios:66a435f7e3fb0af7c8c7c7',
    messagingSenderId: '975792738502',
    projectId: 'test-5f00d',
    storageBucket: 'test-5f00d.appspot.com',
    iosBundleId: 'com.example.practical10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiiZXYccNa5X8ChO07Yz_QMvTrJ4DmR1c',
    appId: '1:975792738502:ios:ed2a56f9a0f3da29c8c7c7',
    messagingSenderId: '975792738502',
    projectId: 'test-5f00d',
    storageBucket: 'test-5f00d.appspot.com',
    iosBundleId: 'com.example.practical10.RunnerTests',
  );
}
